// -------------------------------------------------------------
// 
// File Name: /tmp/tpc580e839_93cc_49a5_b11d_c2360b776e0b/hdlcoder_dspprogfir/coeffs_registers.v
// Created: 2018-12-14 02:36:23
// 
// Generated by MATLAB 9.4 and HDL Coder 3.12
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: coeffs_registers
// Source Path: hdlcoder_dspprogfir/Programmable FIR via Registers/coeffs_registers
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module coeffs_registers
          (clk,
           reset,
           enb,
           coeffs_in,
           write_address,
           write_enable,
           coeffs_out_0,
           coeffs_out_1,
           coeffs_out_2,
           coeffs_out_3,
           coeffs_out_4,
           coeffs_out_5,
           coeffs_out_6,
           coeffs_out_7,
           coeffs_out_8,
           coeffs_out_9,
           coeffs_out_10,
           coeffs_out_11,
           coeffs_out_12,
           coeffs_out_13,
           coeffs_out_14,
           coeffs_out_15,
           coeffs_out_16,
           coeffs_out_17,
           coeffs_out_18,
           coeffs_out_19,
           coeffs_out_20,
           coeffs_out_21,
           coeffs_out_22,
           coeffs_out_23,
           coeffs_out_24,
           coeffs_out_25,
           coeffs_out_26,
           coeffs_out_27,
           coeffs_out_28,
           coeffs_out_29,
           coeffs_out_30,
           coeffs_out_31,
           coeffs_out_32,
           coeffs_out_33,
           coeffs_out_34,
           coeffs_out_35,
           coeffs_out_36,
           coeffs_out_37,
           coeffs_out_38,
           coeffs_out_39,
           coeffs_out_40,
           coeffs_out_41,
           coeffs_out_42);


  input   clk;
  input   reset;
  input   enb;
  input   signed [13:0] coeffs_in;  // sfix14_En13
  input   [7:0] write_address;  // uint8
  input   write_enable;
  output  signed [13:0] coeffs_out_0;  // sfix14_En13
  output  signed [13:0] coeffs_out_1;  // sfix14_En13
  output  signed [13:0] coeffs_out_2;  // sfix14_En13
  output  signed [13:0] coeffs_out_3;  // sfix14_En13
  output  signed [13:0] coeffs_out_4;  // sfix14_En13
  output  signed [13:0] coeffs_out_5;  // sfix14_En13
  output  signed [13:0] coeffs_out_6;  // sfix14_En13
  output  signed [13:0] coeffs_out_7;  // sfix14_En13
  output  signed [13:0] coeffs_out_8;  // sfix14_En13
  output  signed [13:0] coeffs_out_9;  // sfix14_En13
  output  signed [13:0] coeffs_out_10;  // sfix14_En13
  output  signed [13:0] coeffs_out_11;  // sfix14_En13
  output  signed [13:0] coeffs_out_12;  // sfix14_En13
  output  signed [13:0] coeffs_out_13;  // sfix14_En13
  output  signed [13:0] coeffs_out_14;  // sfix14_En13
  output  signed [13:0] coeffs_out_15;  // sfix14_En13
  output  signed [13:0] coeffs_out_16;  // sfix14_En13
  output  signed [13:0] coeffs_out_17;  // sfix14_En13
  output  signed [13:0] coeffs_out_18;  // sfix14_En13
  output  signed [13:0] coeffs_out_19;  // sfix14_En13
  output  signed [13:0] coeffs_out_20;  // sfix14_En13
  output  signed [13:0] coeffs_out_21;  // sfix14_En13
  output  signed [13:0] coeffs_out_22;  // sfix14_En13
  output  signed [13:0] coeffs_out_23;  // sfix14_En13
  output  signed [13:0] coeffs_out_24;  // sfix14_En13
  output  signed [13:0] coeffs_out_25;  // sfix14_En13
  output  signed [13:0] coeffs_out_26;  // sfix14_En13
  output  signed [13:0] coeffs_out_27;  // sfix14_En13
  output  signed [13:0] coeffs_out_28;  // sfix14_En13
  output  signed [13:0] coeffs_out_29;  // sfix14_En13
  output  signed [13:0] coeffs_out_30;  // sfix14_En13
  output  signed [13:0] coeffs_out_31;  // sfix14_En13
  output  signed [13:0] coeffs_out_32;  // sfix14_En13
  output  signed [13:0] coeffs_out_33;  // sfix14_En13
  output  signed [13:0] coeffs_out_34;  // sfix14_En13
  output  signed [13:0] coeffs_out_35;  // sfix14_En13
  output  signed [13:0] coeffs_out_36;  // sfix14_En13
  output  signed [13:0] coeffs_out_37;  // sfix14_En13
  output  signed [13:0] coeffs_out_38;  // sfix14_En13
  output  signed [13:0] coeffs_out_39;  // sfix14_En13
  output  signed [13:0] coeffs_out_40;  // sfix14_En13
  output  signed [13:0] coeffs_out_41;  // sfix14_En13
  output  signed [13:0] coeffs_out_42;  // sfix14_En13


  reg signed [13:0] coeffs_regs [0:42];  // sfix14_En13 [43]
  wire signed [13:0] coeffs_assigned [0:42];  // sfix14_En13 [43]


  assign coeffs_assigned[0] = (write_address == 8'b00000000 ? coeffs_in :
              coeffs_regs[0]);
  assign coeffs_assigned[1] = (write_address == 8'b00000001 ? coeffs_in :
              coeffs_regs[1]);
  assign coeffs_assigned[2] = (write_address == 8'b00000010 ? coeffs_in :
              coeffs_regs[2]);
  assign coeffs_assigned[3] = (write_address == 8'b00000011 ? coeffs_in :
              coeffs_regs[3]);
  assign coeffs_assigned[4] = (write_address == 8'b00000100 ? coeffs_in :
              coeffs_regs[4]);
  assign coeffs_assigned[5] = (write_address == 8'b00000101 ? coeffs_in :
              coeffs_regs[5]);
  assign coeffs_assigned[6] = (write_address == 8'b00000110 ? coeffs_in :
              coeffs_regs[6]);
  assign coeffs_assigned[7] = (write_address == 8'b00000111 ? coeffs_in :
              coeffs_regs[7]);
  assign coeffs_assigned[8] = (write_address == 8'b00001000 ? coeffs_in :
              coeffs_regs[8]);
  assign coeffs_assigned[9] = (write_address == 8'b00001001 ? coeffs_in :
              coeffs_regs[9]);
  assign coeffs_assigned[10] = (write_address == 8'b00001010 ? coeffs_in :
              coeffs_regs[10]);
  assign coeffs_assigned[11] = (write_address == 8'b00001011 ? coeffs_in :
              coeffs_regs[11]);
  assign coeffs_assigned[12] = (write_address == 8'b00001100 ? coeffs_in :
              coeffs_regs[12]);
  assign coeffs_assigned[13] = (write_address == 8'b00001101 ? coeffs_in :
              coeffs_regs[13]);
  assign coeffs_assigned[14] = (write_address == 8'b00001110 ? coeffs_in :
              coeffs_regs[14]);
  assign coeffs_assigned[15] = (write_address == 8'b00001111 ? coeffs_in :
              coeffs_regs[15]);
  assign coeffs_assigned[16] = (write_address == 8'b00010000 ? coeffs_in :
              coeffs_regs[16]);
  assign coeffs_assigned[17] = (write_address == 8'b00010001 ? coeffs_in :
              coeffs_regs[17]);
  assign coeffs_assigned[18] = (write_address == 8'b00010010 ? coeffs_in :
              coeffs_regs[18]);
  assign coeffs_assigned[19] = (write_address == 8'b00010011 ? coeffs_in :
              coeffs_regs[19]);
  assign coeffs_assigned[20] = (write_address == 8'b00010100 ? coeffs_in :
              coeffs_regs[20]);
  assign coeffs_assigned[21] = (write_address == 8'b00010101 ? coeffs_in :
              coeffs_regs[21]);
  assign coeffs_assigned[22] = (write_address == 8'b00010110 ? coeffs_in :
              coeffs_regs[22]);
  assign coeffs_assigned[23] = (write_address == 8'b00010111 ? coeffs_in :
              coeffs_regs[23]);
  assign coeffs_assigned[24] = (write_address == 8'b00011000 ? coeffs_in :
              coeffs_regs[24]);
  assign coeffs_assigned[25] = (write_address == 8'b00011001 ? coeffs_in :
              coeffs_regs[25]);
  assign coeffs_assigned[26] = (write_address == 8'b00011010 ? coeffs_in :
              coeffs_regs[26]);
  assign coeffs_assigned[27] = (write_address == 8'b00011011 ? coeffs_in :
              coeffs_regs[27]);
  assign coeffs_assigned[28] = (write_address == 8'b00011100 ? coeffs_in :
              coeffs_regs[28]);
  assign coeffs_assigned[29] = (write_address == 8'b00011101 ? coeffs_in :
              coeffs_regs[29]);
  assign coeffs_assigned[30] = (write_address == 8'b00011110 ? coeffs_in :
              coeffs_regs[30]);
  assign coeffs_assigned[31] = (write_address == 8'b00011111 ? coeffs_in :
              coeffs_regs[31]);
  assign coeffs_assigned[32] = (write_address == 8'b00100000 ? coeffs_in :
              coeffs_regs[32]);
  assign coeffs_assigned[33] = (write_address == 8'b00100001 ? coeffs_in :
              coeffs_regs[33]);
  assign coeffs_assigned[34] = (write_address == 8'b00100010 ? coeffs_in :
              coeffs_regs[34]);
  assign coeffs_assigned[35] = (write_address == 8'b00100011 ? coeffs_in :
              coeffs_regs[35]);
  assign coeffs_assigned[36] = (write_address == 8'b00100100 ? coeffs_in :
              coeffs_regs[36]);
  assign coeffs_assigned[37] = (write_address == 8'b00100101 ? coeffs_in :
              coeffs_regs[37]);
  assign coeffs_assigned[38] = (write_address == 8'b00100110 ? coeffs_in :
              coeffs_regs[38]);
  assign coeffs_assigned[39] = (write_address == 8'b00100111 ? coeffs_in :
              coeffs_regs[39]);
  assign coeffs_assigned[40] = (write_address == 8'b00101000 ? coeffs_in :
              coeffs_regs[40]);
  assign coeffs_assigned[41] = (write_address == 8'b00101001 ? coeffs_in :
              coeffs_regs[41]);
  assign coeffs_assigned[42] = (write_address == 8'b00101010 ? coeffs_in :
              coeffs_regs[42]);



  always @(posedge clk or posedge reset)
    begin : coeffs_regs_1_process
      if (reset == 1'b1) begin
        coeffs_regs[0] <= 14'sb00000000000000;
        coeffs_regs[1] <= 14'sb00000000000000;
        coeffs_regs[2] <= 14'sb00000000000000;
        coeffs_regs[3] <= 14'sb00000000000000;
        coeffs_regs[4] <= 14'sb00000000000000;
        coeffs_regs[5] <= 14'sb00000000000000;
        coeffs_regs[6] <= 14'sb00000000000000;
        coeffs_regs[7] <= 14'sb00000000000000;
        coeffs_regs[8] <= 14'sb00000000000000;
        coeffs_regs[9] <= 14'sb00000000000000;
        coeffs_regs[10] <= 14'sb00000000000000;
        coeffs_regs[11] <= 14'sb00000000000000;
        coeffs_regs[12] <= 14'sb00000000000000;
        coeffs_regs[13] <= 14'sb00000000000000;
        coeffs_regs[14] <= 14'sb00000000000000;
        coeffs_regs[15] <= 14'sb00000000000000;
        coeffs_regs[16] <= 14'sb00000000000000;
        coeffs_regs[17] <= 14'sb00000000000000;
        coeffs_regs[18] <= 14'sb00000000000000;
        coeffs_regs[19] <= 14'sb00000000000000;
        coeffs_regs[20] <= 14'sb00000000000000;
        coeffs_regs[21] <= 14'sb00000000000000;
        coeffs_regs[22] <= 14'sb00000000000000;
        coeffs_regs[23] <= 14'sb00000000000000;
        coeffs_regs[24] <= 14'sb00000000000000;
        coeffs_regs[25] <= 14'sb00000000000000;
        coeffs_regs[26] <= 14'sb00000000000000;
        coeffs_regs[27] <= 14'sb00000000000000;
        coeffs_regs[28] <= 14'sb00000000000000;
        coeffs_regs[29] <= 14'sb00000000000000;
        coeffs_regs[30] <= 14'sb00000000000000;
        coeffs_regs[31] <= 14'sb00000000000000;
        coeffs_regs[32] <= 14'sb00000000000000;
        coeffs_regs[33] <= 14'sb00000000000000;
        coeffs_regs[34] <= 14'sb00000000000000;
        coeffs_regs[35] <= 14'sb00000000000000;
        coeffs_regs[36] <= 14'sb00000000000000;
        coeffs_regs[37] <= 14'sb00000000000000;
        coeffs_regs[38] <= 14'sb00000000000000;
        coeffs_regs[39] <= 14'sb00000000000000;
        coeffs_regs[40] <= 14'sb00000000000000;
        coeffs_regs[41] <= 14'sb00000000000000;
        coeffs_regs[42] <= 14'sb00000000000000;
      end
      else begin
        if (enb && write_enable) begin
          coeffs_regs[0] <= coeffs_assigned[0];
          coeffs_regs[1] <= coeffs_assigned[1];
          coeffs_regs[2] <= coeffs_assigned[2];
          coeffs_regs[3] <= coeffs_assigned[3];
          coeffs_regs[4] <= coeffs_assigned[4];
          coeffs_regs[5] <= coeffs_assigned[5];
          coeffs_regs[6] <= coeffs_assigned[6];
          coeffs_regs[7] <= coeffs_assigned[7];
          coeffs_regs[8] <= coeffs_assigned[8];
          coeffs_regs[9] <= coeffs_assigned[9];
          coeffs_regs[10] <= coeffs_assigned[10];
          coeffs_regs[11] <= coeffs_assigned[11];
          coeffs_regs[12] <= coeffs_assigned[12];
          coeffs_regs[13] <= coeffs_assigned[13];
          coeffs_regs[14] <= coeffs_assigned[14];
          coeffs_regs[15] <= coeffs_assigned[15];
          coeffs_regs[16] <= coeffs_assigned[16];
          coeffs_regs[17] <= coeffs_assigned[17];
          coeffs_regs[18] <= coeffs_assigned[18];
          coeffs_regs[19] <= coeffs_assigned[19];
          coeffs_regs[20] <= coeffs_assigned[20];
          coeffs_regs[21] <= coeffs_assigned[21];
          coeffs_regs[22] <= coeffs_assigned[22];
          coeffs_regs[23] <= coeffs_assigned[23];
          coeffs_regs[24] <= coeffs_assigned[24];
          coeffs_regs[25] <= coeffs_assigned[25];
          coeffs_regs[26] <= coeffs_assigned[26];
          coeffs_regs[27] <= coeffs_assigned[27];
          coeffs_regs[28] <= coeffs_assigned[28];
          coeffs_regs[29] <= coeffs_assigned[29];
          coeffs_regs[30] <= coeffs_assigned[30];
          coeffs_regs[31] <= coeffs_assigned[31];
          coeffs_regs[32] <= coeffs_assigned[32];
          coeffs_regs[33] <= coeffs_assigned[33];
          coeffs_regs[34] <= coeffs_assigned[34];
          coeffs_regs[35] <= coeffs_assigned[35];
          coeffs_regs[36] <= coeffs_assigned[36];
          coeffs_regs[37] <= coeffs_assigned[37];
          coeffs_regs[38] <= coeffs_assigned[38];
          coeffs_regs[39] <= coeffs_assigned[39];
          coeffs_regs[40] <= coeffs_assigned[40];
          coeffs_regs[41] <= coeffs_assigned[41];
          coeffs_regs[42] <= coeffs_assigned[42];
        end
      end
    end



  assign coeffs_out_0 = coeffs_regs[0];

  assign coeffs_out_1 = coeffs_regs[1];

  assign coeffs_out_2 = coeffs_regs[2];

  assign coeffs_out_3 = coeffs_regs[3];

  assign coeffs_out_4 = coeffs_regs[4];

  assign coeffs_out_5 = coeffs_regs[5];

  assign coeffs_out_6 = coeffs_regs[6];

  assign coeffs_out_7 = coeffs_regs[7];

  assign coeffs_out_8 = coeffs_regs[8];

  assign coeffs_out_9 = coeffs_regs[9];

  assign coeffs_out_10 = coeffs_regs[10];

  assign coeffs_out_11 = coeffs_regs[11];

  assign coeffs_out_12 = coeffs_regs[12];

  assign coeffs_out_13 = coeffs_regs[13];

  assign coeffs_out_14 = coeffs_regs[14];

  assign coeffs_out_15 = coeffs_regs[15];

  assign coeffs_out_16 = coeffs_regs[16];

  assign coeffs_out_17 = coeffs_regs[17];

  assign coeffs_out_18 = coeffs_regs[18];

  assign coeffs_out_19 = coeffs_regs[19];

  assign coeffs_out_20 = coeffs_regs[20];

  assign coeffs_out_21 = coeffs_regs[21];

  assign coeffs_out_22 = coeffs_regs[22];

  assign coeffs_out_23 = coeffs_regs[23];

  assign coeffs_out_24 = coeffs_regs[24];

  assign coeffs_out_25 = coeffs_regs[25];

  assign coeffs_out_26 = coeffs_regs[26];

  assign coeffs_out_27 = coeffs_regs[27];

  assign coeffs_out_28 = coeffs_regs[28];

  assign coeffs_out_29 = coeffs_regs[29];

  assign coeffs_out_30 = coeffs_regs[30];

  assign coeffs_out_31 = coeffs_regs[31];

  assign coeffs_out_32 = coeffs_regs[32];

  assign coeffs_out_33 = coeffs_regs[33];

  assign coeffs_out_34 = coeffs_regs[34];

  assign coeffs_out_35 = coeffs_regs[35];

  assign coeffs_out_36 = coeffs_regs[36];

  assign coeffs_out_37 = coeffs_regs[37];

  assign coeffs_out_38 = coeffs_regs[38];

  assign coeffs_out_39 = coeffs_regs[39];

  assign coeffs_out_40 = coeffs_regs[40];

  assign coeffs_out_41 = coeffs_regs[41];

  assign coeffs_out_42 = coeffs_regs[42];

endmodule  // coeffs_registers

